package remotebackup

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// contentLogEntry is generated by the server, not by the user.
const contentLogEntry = "content.log"

// ProgressFunc reports progress. Fields that do not apply to the current phase
// are left zero.
type ProgressFunc func(phase string, done, total int64, bytes int64)

// SyncOptions describes one sync of a local directory.
type SyncOptions struct {
	Root           string
	Meta           Meta
	IncludeKeys    bool
	IncludeBackups bool
	Progress       ProgressFunc
}

// SyncResult summarises a completed sync.
type SyncResult struct {
	Snapshot      SnapshotInfo
	Duplicate     bool
	Scanned       int
	Present       int
	Uploaded      int
	UploadedBytes int64
}

// Sync hashes every file under opts.Root, uploads only the ones the Backupper
// is missing, then commits a snapshot. Unchanged files transfer zero bytes.
func (c *Client) Sync(opts SyncOptions) (SyncResult, error) {
	var res SyncResult
	report := func(phase string, done, total, bytes int64) {
		if opts.Progress != nil {
			opts.Progress(phase, done, total, bytes)
		}
	}

	report("scanning", 0, 0, 0)
	entries, err := ScanDir(opts.Root, opts.IncludeKeys, opts.IncludeBackups)
	if err != nil {
		return res, err
	}
	res.Scanned = len(entries)
	if len(entries) == 0 {
		return res, fmt.Errorf("nothing to back up: %s contains no files", opts.Root)
	}

	hashes := make([]string, 0, len(entries))
	for _, e := range entries {
		hashes = append(hashes, e.Hash)
	}

	report("checking", 0, int64(len(entries)), 0)
	missing, err := c.Check(hashes)
	if err != nil {
		return res, err
	}
	missingSet := make(map[string]bool, len(missing))
	for _, h := range missing {
		missingSet[h] = true
	}
	res.Present = len(entries) - len(missingSet)

	var done int64
	for _, e := range entries {
		if !missingSet[e.Hash] {
			continue
		}
		if err := uploadEntry(c, opts.Root, e); err != nil {
			return res, err
		}
		res.Uploaded++
		res.UploadedBytes += e.Size
		done++
		report("uploading", done, int64(len(missingSet)), res.UploadedBytes)
	}

	report("committing", done, int64(len(missingSet)), res.UploadedBytes)
	meta := opts.Meta
	meta.IncludeKeys = opts.IncludeKeys
	meta.IncludeBackups = opts.IncludeBackups
	meta.FileCount = len(entries)
	resp, err := c.CommitSnapshot(CreateSnapshotRequest{Meta: meta, Entries: entries})
	if err != nil {
		return res, err
	}
	res.Snapshot = resp.Snapshot
	res.Duplicate = resp.Duplicate
	report("done", done, int64(len(missingSet)), res.UploadedBytes)
	return res, nil
}

func uploadEntry(c *Client, root string, e Entry) error {
	f, err := os.Open(filepath.Join(root, filepath.FromSlash(e.Path)))
	if err != nil {
		return fmt.Errorf("cannot read %s: %w", e.Path, err)
	}
	defer f.Close()
	if _, err := c.PutFile(e.Hash, e.Size, f); err != nil {
		return fmt.Errorf("cannot upload %s: %w", e.Path, err)
	}
	return nil
}

// ScanDir hashes every regular file under root. secrets.json and the chat
// backups/ tree are skipped unless explicitly included, mirroring the local
// export rules.
func ScanDir(root string, includeKeys, includeBackups bool) ([]Entry, error) {
	var entries []Entry
	buf := make([]byte, 1<<20)

	err := filepath.Walk(root, func(path string, fi os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if fi.IsDir() || !fi.Mode().IsRegular() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		slashPath := filepath.ToSlash(rel)
		if slashPath == "secrets.json" && !includeKeys {
			return nil
		}
		if !includeBackups && strings.HasPrefix(slashPath, "backups/") {
			return nil
		}
		// content.log is written by the server's content check on its own
		// schedule. Backing it up would make every sync look "changed" even
		// when the user data is identical.
		if slashPath == contentLogEntry {
			return nil
		}

		f, err := os.Open(path)
		if err != nil {
			return err
		}
		h := sha256.New()
		var total int64
		for {
			n, readErr := f.Read(buf)
			if n > 0 {
				h.Write(buf[:n])
				total += int64(n)
			}
			if readErr == io.EOF {
				break
			}
			if readErr != nil {
				f.Close()
				return readErr
			}
		}
		f.Close()

		var mode uint32
		if runtime.GOOS != "windows" {
			mode = uint32(fi.Mode().Perm())
		}
		entries = append(entries, Entry{
			Path: slashPath,
			Hash: hex.EncodeToString(h.Sum(nil)),
			Size: total,
			Mode: mode,
		})
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
	return entries, nil
}
